spring:
  autoconfigure:
    exclude:  org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5434/task_saas
    username: app
    password: app
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: 8080

app:
  jwt:
    secret: "change_me_to_a_very_long_random_string_at_least_32_chars"
    issuer: "multi-tenant-saas-task-manager"
    accessTokenMinutes: 60
